### PR TITLE
Migrated the documentation from wiki to docs

### PR DESCRIPTION
**Pull request by SebastinSanty**
Issue #1

### CODE REVIEW

**Comment by prasadtalasila** [comment]
The scale of this pull request is huge. Please scale down the scope to one topic and complete that first. 

I would suggest focusing on AutolabJS v0.2.0 documentation first. All the relevant wiki pages have a v0.2.0 prefix. Let's import those documents, link them into the MkDocs and have them properly display on the autolab.github.io/docs website. That would be a good pull request to complete.

**Comment by SebastinSanty** [comment]
@prasadtalasila He cloned the entire wiki, and migrated them to docs. I guess that was a good idea. Also he has modified the links properly.

**Comment by prasadtalasila** [comment]
Migration from wiki to docs is the intention, so more of the same is a certainly good thing. However, I don't see the documents linked on **autolabjs.github.io/docs**. On the website, I see a lone document pertaining to installation of AutolabJS v0.2.0 on a single machine. Nothing else is linked.

In this migration work, one cycle is to take the wiki page, import it into docs/ repository, link the same in MkDocs and have the wiki page available on autolabjs.github.io/docs website. In this pull request, I can see only the import part. That's the reason for the suggestion to scale down the scope, complete the cycle for AutolabJS v0.2,0. Once that work is complete, we can verify the same. After that, rest of the documents can be migrated.

**Comment by SebastinSanty** [comment]
@prasadtalasila The work presently on **autolabjs.github.io/docs** is done by me and it sure has only one link, as I had only migrated one doc.

To make wiki page, one has to send a PR to `gh-pages` too, which is a tedious job. `master` contains a `.gitignore` which ignores the built site. I have asked a very specific question to you related to this on slack. Repeating here -- Github has a new feature that doesn't require the site to be in `gh-pages` branch. We can have the built site in the repo itself. One can select which folder will be shown as website (in our case `site`).

**Comment by prasadtalasila** [comment]
As discussed on slack, the present setup of site from gh-pages is advisable. I agree that separate gh-pages requires two commits (one on master and one on gh-pages) to complete one work cycle.

@GunjanChhablani please send  two coupled pull requests. One pull to master branch and  a coupled pull request to gh-pages branch. Let's do this cycle for two pull requests ; after that we will put in place a shell script to do the job.

**Pull request closed without merging**
